openapi: 3.1.0
info:
  title: Shelf Help API
  version: 1.0.0
paths:
  /api/add_book:
    post:
      summary: Add a new book to the Firebase database
      operationId: addBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Book added successfully

  /api/update_book:
    patch:
      summary: Update an existing book in the Firebase database
      operationId: updateBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - goodreads_id
              additionalProperties: true
      responses:
        '200':
          description: Book updated successfully

  /api/delete_book:
    delete:
      summary: Delete a book from the Firebase database
      operationId: deleteBook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - goodreads_id
              properties:
                goodreads_id:
                  type: string
      responses:
        '200':
          description: Book deleted successfully

  /api/fetch_books:
    post:
      summary: Fetch all or filtered books from Firebase
      operationId: fetchBooks
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Books retrieved successfully

  /api/search_books:
    post:
      summary: Search for a book by title, author, or other fields
      operationId: searchBooks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Matching books returned

  /api/sync_rss:
    post:
      summary: Sync finished books from Goodreads RSS feed
      operationId: syncRSS
      responses:
        '200':
          description: RSS sync triggered

  /api/check_library_holds:
    post:
      summary: Check availability across library and subscription sources
      operationId: checkLibraryHolds
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              additionalProperties: true
      responses:
        '200':
          description: Availability fields updated
