info:
  title: Shelf Help Book API
  version: 1.0.0
openapi: 3.1.0
paths:
  /api/add_book:
    post:
      operationId: api_add_book
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema: &id001
              properties:
                Pubdate:
                  type: string
                author_name:
                  type: string
                availability_source:
                  type: string
                average_rating:
                  type: string
                book_description:
                  type: string
                book_image_url:
                  type: string
                book_large_image_url:
                  type: string
                book_medium_image_url:
                  type: string
                book_published:
                  type: string
                book_small_image_url:
                  type: string
                book_title:
                  type: string
                description_html:
                  type: string
                disliked:
                  type: string
                extras:
                  type: string
                flavor:
                  type: string
                goal_year:
                  type: string
                goodreads_id:
                  type: string
                guid:
                  type: string
                hoopla_audio_available:
                  type: string
                hoopla_ebook_available:
                  type: string
                hype_flag:
                  type: string
                inferred_score:
                  type: string
                isbn:
                  type: string
                ku_availability:
                  type: string
                ku_expires_on:
                  type: string
                library_hold_status_camellia_audio:
                  type: string
                library_hold_status_camellia_ebook:
                  type: string
                library_hold_status_seattle_audio:
                  type: string
                library_hold_status_seattle_ebook:
                  type: string
                library_hold_status_tuscaloosa_audio:
                  type: string
                library_hold_status_tuscaloosa_ebook:
                  type: string
                liked:
                  type: string
                link:
                  type: string
                next_release_date:
                  type: string
                notes:
                  type: string
                pages_source:
                  type: string
                queue_position:
                  type: string
                queue_priority:
                  type: string
                rating_scale_tag:
                  type: string
                series_name:
                  type: string
                series_number:
                  type: string
                status:
                  type: string
                title:
                  type: string
                tone:
                  type: string
                trope:
                  type: string
                updated_at:
                  type: string
                user_date_added:
                  type: string
                user_date_created:
                  type: string
                user_name:
                  type: string
                user_rating:
                  type: string
                user_read_at:
                  type: string
                user_review:
                  type: string
                user_shelves:
                  type: string
              type: object
        required: true
      responses:
        '200':
          description: Successful response
      summary: POST request to /api/add_book
  /api/check_library_holds:
    post:
      operationId: api_check_library_holds
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema: *id001
        required: true
      responses:
        '200':
          description: Successful response
      summary: POST request to /api/check_library_holds
  /api/delete_book:
    delete:
      operationId: api_delete_book
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema:
              properties:
                goodreads_id:
                  type: string
              required:
              - goodreads_id
              type: object
        required: true
      responses:
        '200':
          description: Successful deletion
      summary: DELETE request to /api/delete_book
  /api/fetch_books:
    post:
      operationId: api_fetch_books
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema: *id001
        required: true
      responses:
        '200':
          description: Successful response
      summary: POST request to /api/fetch_books
  /api/search_books:
    post:
      operationId: api_search_books
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema: *id001
        required: true
      responses:
        '200':
          description: Successful response
      summary: POST request to /api/search_books
  /api/sync_rss:
    post:
      operationId: api_sync_rss
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema: *id001
        required: true
      responses:
        '200':
          description: Successful response
      summary: POST request to /api/sync_rss
  /api/update_book:
    patch:
      operationId: api_update_book
      x-openai-isConsequential: false
      requestBody:
        content:
          application/json:
            schema: *id001
        required: true
      responses:
        '200':
          description: Successful response
      summary: PATCH request to /api/update_book
servers:
- url: https://book-gpt-api.vercel.app
