name: python-tests

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm i -g vercel@latest

      - name: Deploy (prebuilt -> prod)
        run: vercel deploy --prebuilt --prod --yes

  tests:
    runs-on: ubuntu-latest
    needs: deploy          # wait for deploy job
    env:
      BASE_URL: https://book-gpt-api.vercel.app
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
          cache: pip

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest requests python-dotenv

      - name: Run pytest
        run: pytest -v