name: Sync Goodreads RSS

# triggers twice daily at 7:30 PM Central (00:30 & 12:30 UTC)
on:
  schedule:
    - cron: '30 00 * * *'
    - cron: '30 12 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Goodreads RSS sync
        run: curl -X GET https://book-gpt-api.vercel.app/api/sync_rss