name: Sync Goodreads RSS

on:
  schedule:
    # 07:30 PM & 07:30 AM Central Time
    - cron: '30 00 * * *'
    - cron: '30 12 * * *'
  workflow_dispatch:  # lets you run it by hand

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Goodreads RSS sync
        run: curl -sS https://book-gpt-api.vercel.app/api/sync_rss