name: Sync Goodreads RSS

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch:       # keep manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Goodreads RSS sync
        run: curl -sS https://book-gpt-api.vercel.app/api/sync_rss